#!/usr/bin/env bash

SKIP_FILE=~/.skip-dotfiles-bootstrap

# skip if we've done this in the last 12 hours
if find "$SKIP_FILE" -mtime -12 2>/dev/null | grep -q -P '.*'; then
  exit 0
fi

touch "$SKIP_FILE"

for profile
do
  cd $profile

  find . -name '*.symlink' -print0 | while read -d $'\0' dotslashfile
  do
    file="$(echo "${dotslashfile:2}")"
    file_no_symlink="$(echo "${file::-8}")"
    linkfile=$HOME/$file_no_symlink
    linkto=$profile/$file
    if [ -f $linkfile ] || [ -d $linkfile ] || [ -L $linkfile ]
    then
      existing="$(readlink $linkfile)"
      if [ "$linkto" != "$existing" ]
      then
        echo "Warning! Existing dotfile is not the correct symlink: $linkfile"
        echo "(Due to $linkto != $existing)"
        rm -f $SKIP_FILE
      fi
    else
      echo "Linking $linkfile to $linkto"
      parent="$(dirname $linkfile)"
      mkdir -p $parent &>/dev/null
      ln -s $linkto $linkfile
    fi
  done
done
