#!/usr/bin/env bash

PROFILES_CACHE_FILE=~/.dotfiles-profiles
X=("$@")
EXPECTED="$(IFS=$'\n'; echo "${X[*]}"; )"
if [[ -f "$PROFILES_CACHE_FILE" ]]; then
    ACTUAL="$(cat "$PROFILES_CACHE_FILE")"
    if [[ "$ACTUAL" != "$EXPECTED" ]]; then
       echo >&2 "Profiles cache file mismatch -- expected[$EXPECTED] actual[$ACTUAL]"
       echo >&2 "Maybe rm $PROFILES_CACHE_FILE"
       exit 1
    fi
else
    echo "$EXPECTED" > "$PROFILES_CACHE_FILE"
fi

mkdir -p ~/bin
SKIP_FILE=~/bin/.dotfiles-created
if [[ ! -f $SKIP_FILE ]]; then
    $(dirname "$0")/base/bin/create-dotfiles-symlinks.symlink && touch $SKIP_FILE
fi
